name: Execute each 30 minutes

on:
    workflow_dispatch:

jobs:
    execute:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Execute curl
              run: |
                    echo "3" > ./count.txt
                    cat ./count.txt
                    c=$(cat ./count.txt); [ $c -ge 3 ] && curl -s -X POST "https://api.telegram.org/bot${{ secrets.TOKENTELEGRAM }}/sendMessage" -d chat_id="${{ secrets.CHATIDTELEGRAM }}" -d text="🚨 SIN CUPOS" || echo "Hay cupos disponibles ($c)"
